# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
        gradle-version: 8.1.1
        arguments: build publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    - uses: Kir-Antipov/mc-publish@v3.2
#      with:
#        version-type: alpha
#        dependencies: ""
#        changelog: ""
#
#        files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
#        files-secondary: ""
#
#        modrinth-id: bqOyYdKi
#        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
#        modrinth-featured: false
#
#        github-token: ${{ secrets.GITHUB_TOKEN }}
